version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  main_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    working_dir: /SU_SOFT
    command: python main.py
    depends_on:
      - db

  nextgen_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    working_dir: /SU_SOFT
    command: python nextgen.py
    depends_on:
      - db

volumes:
  pgdata:
    driver: local