version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  main_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    working_dir: /SU_SOFT
    command: sh -c "alembic upgrade head && python main.py"
    depends_on:
      - db

volumes:
  pgdata:
    driver: local